# Generated by Django 4.2.16 on 2024-10-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app11', '0002_alter_coords_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(default=True),
        ),
    ]
